baseurl = "https://hmjianggatech.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "news"
  showNews = false
  showSections = ["research", "projects", "others"]

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.news]
  name = "News"
  url = "/news"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Haoming Jiang"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Haoming Jiang"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "research"
        name = "Research"
        url = "/research"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "news"
        name = "News"
        url = "/news"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "others"
        name = "Others"
        url = "/others"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "gallery"
        name = "Gallery"
        url = "/gallery"
        weight = 6
